name: test for repository_dispatch - acceptor side

on: 
  push:

  repository_dispatch:

  workflow_dispatch:
    inputs:

      arg1:
        description: 'argument number 1'
        required: true
        default: default-1

      arg2:
        description: 'argument number 2'
        required: false

      arg3:
        description: 'argument number 3'
        required: false
        default: default-3

jobs:

  dispatch:

    runs-on: ubuntu-latest

    steps:

      - name: dispatched event
        run: |
	  echo AAA
